### ISSUE TITLE
OOM Error in GDG Finder app

### ISSUE THREAD

**Issue by tr15tan** [google-developer-training/android-kotlin-fundamentals-starter-apps#31]
I cloned this repository in 2020/08/24, import, build and install the GDG Finder app in my phone(Android Version 7.1.1), and every time i start the app, it will crash immediately. Here is the log:
```
2020-08-25 10:21:49.842 15366-15366/com.example.android.gdgfinder W/System: ClassLoader referenced unknown path: /data/app/com.example.android.gdgfinder-1/lib/arm
2020-08-25 10:21:49.918 15366-15366/com.example.android.gdgfinder W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art: Rejecting re-init on previously-failed class java.lang.Class<androidx.core.view.ViewCompat$2>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/View$OnUnhandledKeyEventListener;
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2436)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at androidx.databinding.ViewDataBinding androidx.databinding.DataBindingUtil.setContentView(android.app.Activity, int, androidx.databinding.DataBindingComponent) (DataBindingUtil.java:303)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at androidx.databinding.ViewDataBinding androidx.databinding.DataBindingUtil.setContentView(android.app.Activity, int) (DataBindingUtil.java:284)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void com.example.android.gdgfinder.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:40)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6687)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1150)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2680)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2806)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1511)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.os.Looper.loop() (Looper.java:154)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6259)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:891)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:781)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/data/app/com.example.android.gdgfinder-1/base.apk"],nativeLibraryDirectories=[/data/app/com.example.android.gdgfinder-1/lib/arm, /system/lib, /vendor/lib]]
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at java.lang.Class dalvik.system.BaseDexClassLoader.findClass(java.lang.String) (BaseDexClassLoader.java:56)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String, boolean) (ClassLoader.java:380)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String) (ClassLoader.java:312)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void androidx.core.view.ViewCompat.setOnApplyWindowInsetsListener(android.view.View, androidx.core.view.OnApplyWindowInsetsListener) (ViewCompat.java:2436)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at android.view.ViewGroup androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor() (AppCompatDelegateImpl.java:779)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor() (AppCompatDelegateImpl.java:659)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void androidx.appcompat.app.AppCompatDelegateImpl.setContentView(int) (AppCompatDelegateImpl.java:552)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void androidx.appcompat.app.AppCompatActivity.setContentView(int) (AppCompatActivity.java:161)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at androidx.databinding.ViewDataBinding androidx.databinding.DataBindingUtil.setContentView(android.app.Activity, int, androidx.databinding.DataBindingComponent) (DataBindingUtil.java:303)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at androidx.databinding.ViewDataBinding androidx.databinding.DataBindingUtil.setContentView(android.app.Activity, int) (DataBindingUtil.java:284)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void com.example.android.gdgfinder.MainActivity.onCreate(android.os.Bundle) (MainActivity.kt:40)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.Activity.performCreate(android.os.Bundle) (Activity.java:6687)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.Instrumentation.callActivityOnCreate(android.app.Activity, android.os.Bundle) (Instrumentation.java:1150)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at android.app.Activity android.app.ActivityThread.performLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent) (ActivityThread.java:2680)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.ActivityThread.handleLaunchActivity(android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:2806)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.ActivityThread.-wrap12(android.app.ActivityThread, android.app.ActivityThread$ActivityClientRecord, android.content.Intent, java.lang.String) (ActivityThread.java:-1)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.ActivityThread$H.handleMessage(android.os.Message) (ActivityThread.java:1511)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.os.Handler.dispatchMessage(android.os.Message) (Handler.java:102)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.os.Looper.loop() (Looper.java:154)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void android.app.ActivityThread.main(java.lang.String[]) (ActivityThread.java:6259)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at java.lang.Object java.lang.reflect.Method.invoke!(java.lang.Object, java.lang.Object[]) (Method.java:-2)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run() (ZygoteInit.java:891)
2020-08-25 10:21:49.953 15366-15366/com.example.android.gdgfinder I/art:     at void com.android.internal.os.ZygoteInit.main(java.lang.String[]) (ZygoteInit.java:781)
2020-08-25 10:21:50.191 15366-15366/com.example.android.gdgfinder I/ViewConfigCompat: Could not find method getScaledScrollFactor() on ViewConfiguration
2020-08-25 10:21:51.301 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.301 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.309 15366-15366/com.example.android.gdgfinder I/art: Alloc sticky concurrent mark sweep GC freed 96(24KB) AllocSpace objects, 0(0B) LOS objects, 10% free, 139MB/155MB, paused 414us total 7.806ms
2020-08-25 10:21:51.309 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.328 15366-15366/com.example.android.gdgfinder I/art: Alloc partial concurrent mark sweep GC freed 51(2112B) AllocSpace objects, 0(0B) LOS objects, 10% free, 139MB/155MB, paused 418us total 18.928ms
2020-08-25 10:21:51.328 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.360 15366-15366/com.example.android.gdgfinder I/art: Alloc concurrent mark sweep GC freed 5(152B) AllocSpace objects, 0(0B) LOS objects, 10% free, 139MB/155MB, paused 431us total 31.797ms
2020-08-25 10:21:51.360 15366-15366/com.example.android.gdgfinder I/art: Forcing collection of SoftReferences for 102MB allocation
2020-08-25 10:21:51.360 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.392 15366-15366/com.example.android.gdgfinder I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 10% free, 139MB/155MB, paused 443us total 31.117ms
2020-08-25 10:21:51.392 15366-15366/com.example.android.gdgfinder W/art: Throwing OutOfMemoryError "Failed to allocate a 108000012 byte allocation with 16765936 free bytes and 52MB until OOM"
2020-08-25 10:21:51.392 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.392 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.399 15366-15366/com.example.android.gdgfinder I/art: Alloc sticky concurrent mark sweep GC freed 4(1536B) AllocSpace objects, 0(0B) LOS objects, 10% free, 139MB/155MB, paused 412us total 6.554ms
2020-08-25 10:21:51.399 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.418 15366-15366/com.example.android.gdgfinder I/art: Alloc partial concurrent mark sweep GC freed 6(144B) AllocSpace objects, 0(0B) LOS objects, 10% free, 139MB/155MB, paused 419us total 18.845ms
2020-08-25 10:21:51.418 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.450 15366-15366/com.example.android.gdgfinder I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 10% free, 139MB/155MB, paused 438us total 31.105ms
2020-08-25 10:21:51.450 15366-15366/com.example.android.gdgfinder I/art: Forcing collection of SoftReferences for 102MB allocation
2020-08-25 10:21:51.450 15366-15366/com.example.android.gdgfinder I/art: Starting a blocking GC Alloc
2020-08-25 10:21:51.481 15366-15366/com.example.android.gdgfinder I/art: Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 10% free, 139MB/155MB, paused 452us total 31.081ms
2020-08-25 10:21:51.481 15366-15366/com.example.android.gdgfinder W/art: Throwing OutOfMemoryError "Failed to allocate a 108000012 byte allocation with 16765936 free bytes and 52MB until OOM"
2020-08-25 10:21:51.482 15366-15366/com.example.android.gdgfinder D/skia: --- allocation failed for scaled bitmap
2020-08-25 10:21:51.483 15366-15366/com.example.android.gdgfinder D/AndroidRuntime: Shutting down VM
    
    
    --------- beginning of crash
2020-08-25 10:21:51.484 15366-15366/com.example.android.gdgfinder E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.android.gdgfinder, PID: 15366
    java.lang.OutOfMemoryError: Failed to allocate a 108000012 byte allocation with 16765936 free bytes and 52MB until OOM
        at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
        at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
        at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1155)
        at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:879)
        at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:730)
        at android.content.res.ResourcesImpl.getDrawable(ResourcesImpl.java:288)
        at android.content.res.Resources.getDrawable(Resources.java:792)
        at android.content.Context.getDrawable(Context.java:525)
        at androidx.core.content.ContextCompat.getDrawable(ContextCompat.java:454)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:144)
        at androidx.appcompat.widget.ResourceManagerInternal.getDrawable(ResourceManagerInternal.java:132)
        at androidx.appcompat.content.res.AppCompatResources.getDrawable(AppCompatResources.java:104)
        at androidx.appcompat.widget.AppCompatImageHelper.loadFromAttributes(AppCompatImageHelper.java:59)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:78)
        at androidx.appcompat.widget.AppCompatImageView.<init>(AppCompatImageView.java:68)
        at androidx.appcompat.app.AppCompatViewInflater.createImageView(AppCompatViewInflater.java:187)
        at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:107)
        at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1407)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1457)
        at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:192)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:769)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:126)
        at androidx.databinding.ViewDataBinding.inflateInternal(ViewDataBinding.java:1368)
        at com.example.android.gdgfinder.databinding.HomeFragmentBinding.inflate(HomeFragmentBinding.java:93)
        at com.example.android.gdgfinder.databinding.HomeFragmentBinding.inflate(HomeFragmentBinding.java:79)
        at com.example.android.gdgfinder.home.HomeFragment.onCreateView(HomeFragment.kt:40)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
2020-08-25 10:21:51.485 15366-15366/com.example.android.gdgfinder E/AndroidRuntime:     at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1280)
        at android.app.Activity.performStart(Activity.java:6704)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2690)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2806)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1511)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6259)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
2020-08-25 10:21:51.496 15366-15366/com.example.android.gdgfinder I/Process: Sending signal. PID: 15366 SIG: 9

```

**Comment by jtavva** [comment]
@tr15tan Thank you for reporting. Are you facing this issue on the emulator as well?

**Comment by tr15tan** [comment]
> @tr15tan Thank you for reporting. Are you facing this issue on the emulator as well?

No, it works fine in the emulator with target API25 Google APIs Image.

**Comment by jtavva** [comment]
@tr15tan, thank you for the response, I think your device is low on RAM.
To allow multiple running processes, Android sets a hard limit on the heap size allotted for each app. The exact heap size limit varies between devices based on how much RAM the device has available overall. To address this issue in this codelab and code sample is way out of scope. 
Closing this issue this issue as this app is running with out any issues in other devices and on Emulator. Thank you for reporting!
